{{- if .Values.npuExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: npu-exporter
  labels:
    app: npu-exporter
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: http
      protocol: TCP
      name: npu-metrics
  selector:
    app: npu-exporter
{{- end }}